#!/usr/bin/env node
/**
 * Truck Route Planner - assemble www/ for the native iOS build.
 *
 *     node tools/build-app.js
 *
 * Capacitor packages one directory. This copies the web app into www/ and
 * makes the three changes a packaged build needs, none of which should apply
 * to the website:
 *
 *   1. index.html becomes a straight jump to the mobile build. On the web that
 *      page detects the device and offers a choice, which is pointless inside
 *      an app the user installed on a phone.
 *   2. The service worker is not copied and its registration is removed. In a
 *      packaged app every asset is already local, so a second cache layer adds
 *      nothing and turns "reinstall the app" into a way to serve stale files.
 *   3. The backend, tests and tooling are left out. They are not part of the
 *      shipped app and would only inflate the bundle.
 *
 * created by Gabor Gasko
 */
'use strict';

const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const out = path.join(root, 'www');

/* Everything the app needs at runtime, and nothing else. */
const COPY_DIRS = ['css', 'js', 'data', 'assets'];
const COPY_FILES = [
  'mobile.html',
  'desktop.html',
  'USER_GUIDE.html',
  'PRIVACY.html',
  'manifest.webmanifest'
];

/* Never shipped: server code, tests, build tooling, local state. */
const EXCLUDE_DIRS = new Set(['node_modules', '.git', '.wrangler', 'ios', 'android', 'www']);

function rmrf(target) {
  if (fs.existsSync(target)) fs.rmSync(target, { recursive: true, force: true });
}

function copyDir(from, to) {
  fs.mkdirSync(to, { recursive: true });
  fs.readdirSync(from, { withFileTypes: true }).forEach((entry) => {
    if (EXCLUDE_DIRS.has(entry.name)) return;
    const src = path.join(from, entry.name);
    const dst = path.join(to, entry.name);
    if (entry.isDirectory()) copyDir(src, dst);
    else fs.copyFileSync(src, dst);
  });
}

/**
 * Strip the service worker registration from a page.
 * Left in, it would register a worker whose script was never copied, which
 * fails silently on every launch and leaves a misleading console error.
 */
function stripServiceWorker(html) {
  return html
    .replace(/[ \t]*<script>[^<]*serviceWorker[\s\S]*?<\/script>\r?\n?/g, '')
    .replace(/[ \t]*navigator\.serviceWorker\.register\([^)]*\);?\r?\n?/g, '');
}

/** The entry point Capacitor loads. */
function nativeIndex() {
  return [
    '<!doctype html>',
    '<html lang="es">',
    '<head>',
    '<meta charset="utf-8">',
    '<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">',
    '<title>Planificador de ruta - Gabor</title>',
    '<!--',
    '  GENERATED by tools/build-app.js - do not edit.',
    '',
    '  The website\'s index.html detects the device and offers a choice between',
    '  the two builds. Inside an app installed on a phone that question is',
    '  already answered, so the packaged entry point goes straight to the',
    '  mobile build instead of showing a splash nobody needs.',
    '-->',
    '<meta http-equiv="refresh" content="0; url=mobile.html?view=mobile">',
    '<script>location.replace("mobile.html?view=mobile");</script>',
    '</head>',
    '<body style="margin:0;background:#0b1220"></body>',
    '</html>',
    ''
  ].join('\n');
}

function build() {
  rmrf(out);
  fs.mkdirSync(out, { recursive: true });

  COPY_DIRS.forEach((dir) => {
    const from = path.join(root, dir);
    if (fs.existsSync(from)) copyDir(from, path.join(out, dir));
  });

  COPY_FILES.forEach((file) => {
    const from = path.join(root, file);
    if (!fs.existsSync(from)) return;
    const html = /\.html$/.test(file)
      ? stripServiceWorker(fs.readFileSync(from, 'utf8'))
      : fs.readFileSync(from, 'utf8');
    fs.writeFileSync(path.join(out, file), html, 'utf8');
  });

  fs.writeFileSync(path.join(out, 'index.html'), nativeIndex(), 'utf8');

  /* A quick sanity report, because a silently short build is hard to spot. */
  let files = 0;
  let bytes = 0;
  (function walk(dir) {
    fs.readdirSync(dir, { withFileTypes: true }).forEach((e) => {
      const p = path.join(dir, e.name);
      if (e.isDirectory()) walk(p);
      else { files += 1; bytes += fs.statSync(p).size; }
    });
  })(out);

  process.stdout.write('www/ built: ' + files + ' files, ' +
    (bytes / 1024 / 1024).toFixed(2) + ' MB\n');

  const leftover = fs.existsSync(path.join(out, 'sw.js'));
  if (leftover) throw new Error('sw.js reached www/ - it must not be packaged');

  return { files, bytes };
}

if (require.main === module) build();

module.exports = { build, stripServiceWorker, nativeIndex, COPY_DIRS, COPY_FILES };
